#pragma once

enum MessageType : unsigned __int8
{
	ENEMY_POSITION_UPDATE,
	RESIZE_ENEMIES,

	BULLET_POSITION_UPDATE,
	RESIZE_BULLETS,

	POWERUP_POSITION_UPDATE,
	RESIZE_POWERUPS,

	PLAYER_POSITION_UPDATE,
	PLAYER_SPECIFIC_UPDATE,
	PLAYER_TRY_FIRE,
	PLAYER_HIT_BY_BULLET,

	MESSAGETYPE_NUM_ITEMS
};